#!/bin/sh -e
### BEGIN INIT INFO
# Provides:          qlauncher
# Required-Start:    mountvirtfs
# Required-Stop:
# Should-Start:
# Should-Stop:
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Qt launcher
### END INIT INFO

PATH="/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin"

# Load default env variables from profiles(e.g. /etc/profile.d/qlauncher.sh)
. /etc/profile

start_qlauncher()
{
	WAYLAND_WAIT=1 /usr/bin/jssServer
}

stop_qlauncher()
{
	killall jssServer
}

case "$1" in
	start)
		echo "starting jssServer... "
		start_qlauncher&
		;;
	stop)
		echo -n "stoping jssServer... "
		stop_qlauncher
		echo "done."
		;;
	restart|reload)
		echo -n "stoping jssServer... "
		stop_qlauncher && sleep .3
		echo "done."

		echo "starting jssServer... "
		start_qlauncher&
		;;
	*)
		echo "Usage: $0 {start|stop|restart}"
		exit 1
esac

exit 0
